/**
 * Generated Official GHL Spec Tools
 *
 * This file is generated by scripts/generate-official-spec-tools.mjs from
 * docs/ghl-api-coverage.json, which is produced from the official
 * GoHighLevel/highlevel-api-docs OpenAPI fragments.
 *
 * Do not hand-edit endpoint definitions here. Refresh with:
 *   npm run scan:ghl-api
 *   node scripts/generate-official-spec-tools.mjs
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { GHLToolClient, HttpMethod } from './ghl-tool-client.js';

interface OfficialEndpoint {
  name: string;
  method: HttpMethod;
  path: string;
  app: string;
  summary: string;
  operationId: string;
  versions: string[];
  scopes: string[];
  pathParams: string[];
  queryParams: Array<{
    name: string;
    required?: boolean;
    schema?: Record<string, unknown>;
    description?: string;
  }>;
  requestBodySchema?: Record<string, unknown>;
}

const ENDPOINTS = JSON.parse(readFileSync(resolveEndpointDataPath(), 'utf8')) as OfficialEndpoint[];

export class OfficialSpecTools {
  constructor(private ghlClient: GHLToolClient) {}

  getToolDefinitions() {
    return ENDPOINTS.map((endpoint) => ({
      name: endpoint.name,
      description: [
        endpoint.summary,
        `Official GHL API endpoint: ${endpoint.method} ${endpoint.path}.`,
        endpoint.scopes.length ? `Scopes: ${endpoint.scopes.join(', ')}.` : '',
      ].filter(Boolean).join(' '),
      inputSchema: this.buildInputSchema(endpoint),
      _meta: {
        labels: {
          category: `official-${endpoint.app}`,
          access: endpoint.method === 'GET' ? 'read' : endpoint.method === 'DELETE' ? 'delete' : 'write',
          complexity: 'generated',
          source: 'official-ghl-openapi',
        },
        official: {
          app: endpoint.app,
          operationId: endpoint.operationId,
          method: endpoint.method,
          path: endpoint.path,
          versions: endpoint.versions,
          scopes: endpoint.scopes,
        },
      },
    }));
  }

  async handleToolCall(toolName: string, args: Record<string, unknown>): Promise<unknown> {
    const endpoint = ENDPOINTS.find((item) => item.name === toolName);
    if (!endpoint) throw new Error(`Unknown official spec tool: ${toolName}`);

    const config = this.ghlClient.getConfig();
    const path = this.buildPath(endpoint, args, config.locationId);
    const body = this.buildBody(endpoint, args);

    const version = endpoint.versions[0];
    return this.ghlClient.makeRequest(endpoint.method, path, body, version ? { version } : undefined);
  }

  private buildInputSchema(endpoint: OfficialEndpoint) {
    const properties: Record<string, unknown> = {};
    const required: string[] = [];

    for (const name of endpoint.pathParams) {
      properties[name] = { type: 'string', description: `Path parameter: ${name}` };
      required.push(name);
    }

    for (const param of endpoint.queryParams) {
      properties[param.name] = this.toInputProperty(param.schema, param.description || `Query parameter: ${param.name}`);
      if (param.required && param.name !== 'locationId') required.push(param.name);
    }

    if (endpoint.method !== 'GET' && endpoint.method !== 'DELETE') {
      properties.body = {
        type: 'object',
        description: 'Request body. When omitted, non-path and non-query arguments are sent as the JSON body.',
        additionalProperties: true,
        ...(endpoint.requestBodySchema || {}),
      };
    }

    return {
      type: 'object',
      properties,
      required,
      additionalProperties: true,
    };
  }

  private buildPath(endpoint: OfficialEndpoint, args: Record<string, unknown>, defaultLocationId: string): string {
    let path = endpoint.path;

    for (const param of endpoint.pathParams) {
      const value = args[param];
      if (value === undefined || value === null || value === '') {
        throw new Error(`Missing required path parameter: ${param}`);
      }
      path = path.replace(new RegExp(`\\{${escapeRegExp(param)}\\}`, 'g'), encodeURIComponent(String(value)));
    }

    const query = new URLSearchParams();
    for (const param of endpoint.queryParams) {
      const value = args[param.name] ?? (param.name === 'locationId' ? defaultLocationId : undefined);
      if (value === undefined || value === null || value === '') continue;
      appendQueryParam(query, param.name, value);
    }

    const queryString = query.toString();
    return queryString ? `${path}?${queryString}` : path;
  }

  private buildBody(endpoint: OfficialEndpoint, args: Record<string, unknown>): Record<string, unknown> | undefined {
    if (endpoint.method === 'GET' || endpoint.method === 'DELETE') return undefined;
    if (isRecord(args.body)) return args.body;

    const excluded = new Set([...endpoint.pathParams, ...endpoint.queryParams.map((param) => param.name), 'body']);
    const body: Record<string, unknown> = {};
    for (const [key, value] of Object.entries(args)) {
      if (!excluded.has(key)) body[key] = value;
    }
    return Object.keys(body).length > 0 ? body : undefined;
  }

  private toInputProperty(schema: Record<string, unknown> | undefined, description: string): Record<string, unknown> {
    const property = sanitizeSchema(schema);
    return {
      type: property.type || 'string',
      ...property,
      description,
    };
  }
}

function appendQueryParam(query: URLSearchParams, name: string, value: unknown): void {
  if (Array.isArray(value)) {
    for (const item of value) query.append(name, String(item));
    return;
  }
  query.append(name, String(value));
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function sanitizeSchema(schema: Record<string, unknown> | undefined): Record<string, unknown> {
  if (!schema) return {};
  const allowed = new Set(['type', 'enum', 'items', 'format', 'default', 'minimum', 'maximum', 'minLength', 'maxLength']);
  const clean: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(schema)) {
    if (allowed.has(key)) clean[key] = value;
  }
  return clean;
}

function resolveEndpointDataPath(): string {
  const candidates = [
    join(__dirname, 'official-spec-endpoints.json'),
    join(process.cwd(), 'src', 'tools', 'official-spec-endpoints.json'),
    join(process.cwd(), 'dist', 'tools', 'official-spec-endpoints.json'),
  ];

  for (const candidate of candidates) {
    try {
      readFileSync(candidate, 'utf8');
      return candidate;
    } catch {
      // Try the next known build/dev location.
    }
  }

  return candidates[0];
}
